name: Deploy to Cloudflare

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 允許手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_TAPPAY_APP_KEY: ${{ secrets.VITE_TAPPAY_APP_KEY }}
      VITE_TAPPAY_APP_ID: ${{ secrets.VITE_TAPPAY_APP_ID }}
      VITE_APPLE_MERCHANT_ID: ${{ secrets.VITE_APPLE_MERCHANT_ID }}
      VITE_GOOGLE_MERCHANT_ID: ${{ secrets.VITE_GOOGLE_MERCHANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project with Vite
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: conf-give-fe
          directory: dist
          wranglerVersion: '3'
